os:
  - linux
  - osx

# in theory travis should detect what to install,
# but we use meson, which is not supported by travis yet and we need custom commands
compiler:
  - gcc

language: c

env:
  global:
    DATETIME=$(date +%Y%m%d-%H%M%S)

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: 
        TARGET=linux-amd64
        EXTENSION=
    - os: linux
      dist: trusty
      sudo: required
      env:
        TARGET=linux-armhf
        EXTENSION=
    - os: linux
      dist: trusty
      sudo: required
      env:
        TARGET=linux-i686
        EXTENSION=
    - os: linux
      dist: trusty
      sudo: required
      env:
        TARGET=windows-x86
        EXTENSION=.exe
    - os: linux
      dist: trusty
      sudo: required
      env:
        TARGET=windows-x64
        EXTENSION=.exe
    - os: osx
      env:
        TARGET=darwin-amd64
        EXTENSION=
  exclude:
    compiler: gcc

addons:
    apt:
      update: true
      packages:
        build-essential
        python-virtualenv
        python3-dev
        python3-pip
        ninja-build
        cmake
        gcc-multilib

before_install:
  # show some extra info
  - export | sort
  - env | sort
  # Setup macos build environment
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install meson ninja; fi
  # ensure we do not have curl dev libs, otherwise it caused cross compilations to fail
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y remove libcurl.*-dev; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y remove libpcre*-dev; fi
  # install cross complier if we gonna do binaries for windows
  - if [ -z "${TARGET##*windows*}" ]; then sudo apt-get -y install mingw-w64 ; fi
  # install cross compiler tools if we gonna do binares for arm/raspberry
  # notice it will remove gcc-multilib
  - if [ -z "${TARGET##*arm*}" ]; then sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf ;fi
  # activate virtualenv with python3, meson requires python3
  - if [ $TRAVIS_OS_NAME = linux ]; then virtualenv .venv --python=python3; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then . .venv/bin/activate; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pip3 install --upgrade pip; fi
  # install python packages like meson, ninja etc...
  - if [ $TRAVIS_OS_NAME = linux ]; then pip3 install -r requirements.txt; fi

# each script section is executed in matrix build
script:
  - echo TARGET=${TARGET}
  - mkdir build_${TARGET} || true
  - meson build_${TARGET} --cross-file tools/cross-compilation/${TARGET}.txt
  - ninja -v -C build_${TARGET}
  # print basic info about compiled files
  - file build_${TARGET}/mvdsv${EXTENSION}
  - mkdir -p uploads_to_gcs
  - mv build_${TARGET}/mvdsv${EXTENSION} uploads_to_gcs/${DATETIME}_${TRAVIS_COMMIT:0:7}_mvdsv${EXTENSION}

deploy:
  provider: gcs
  access_key_id: GOOGIDU6SZSRYABCDMPF
  secret_access_key:
    secure: "Mz9ekafJMVUEjWeKA7hK+4UhDRyp74cZgAcWXozO54jb/NyyfzZWthr3Lu/41LwXrcSVWGruQTrcAvBt3jzm+v9X2lCAnBOENisbBu/HegCAdMt2XTRud9lisaL5IMiPIaA4sAPjlfkkHo9yxQqzXhF2/IqOiNYiDcUAKeXcvLY="
  bucket: mvdsv
  on:
    repo: deurk/mvdsv
  skip_cleanup: true
  upload-dir: commits/${TARGET}
  local-dir: uploads_to_gcs
  acl: public-read

