dist: focal

os:
  - linux

compiler:
  - gcc

language: c

env:
  global:
    DATETIME=$(date +%Y%m%d-%H%M%S)
    DATE=${DATETIME%%-*}
    TIME=${DATETIME##*-}

jobs:
  include:
    - os: linux
      env:
        OS=linux
        ARCH=amd64
        EXTENSION=
    - os: linux
      env:
        OS=linux
        ARCH=i686
        EXTENSION=
    - os: linux
      env:
        OS=linux
        ARCH=armhf
        EXTENSION=
    - os: linux
      env:
        OS=linux
        ARCH=aarch64
        EXTENSION=
    - os: linux
      env:
        OS=windows
        ARCH=x64
        EXTENSION=.exe
      addons:
        apt:
          packages:
            - mingw-w64
    - os: linux
      env:
        OS=windows
        ARCH=x86
        EXTENSION=.exe
      addons:
        apt:
          packages:
            - mingw-w64

addons:
  apt:
    update: true
    packages:
      build-essential
      python-virtualenv
      python3-dev
      python3-pip
      ninja-build
      cmake
      gcc-multilib

before_install:
  # install cross compiler tools if we are going to compile binares for arm (notice it will remove gcc-multilib and creates a dependency issue if we try to install those packages with the others)
  - if [ -z "${ARCH##armhf}" ]; then sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-armel-cross ;fi
  - if [ -z "${ARCH##aarch64}" ]; then sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross ;fi
  # activate virtualenv with python3, meson requires python3
  - virtualenv .venv --python=python3
  - . .venv/bin/activate
  - pip3 install --upgrade pip
  # install python packages like meson, ninja etc...
  - pip3 install -r requirements.txt

before_script:
  # add current commit ref to include files for debugging ease
  - sed -i "s/#define GIT_COMMIT.*$/$(git log -n 1 --format=format:"#define GIT_COMMIT \"%h\"" HEAD)/" src/version.h

script:
  # build binary
  - meson build --buildtype=release --cross-file tools/cross-compilation/${OS}-${ARCH}.txt
  - ninja -v -C build

after_success:
  - export BINARY=mvdsv${EXTENSION}
  - export CHECKSUM=mvdsv.md5
  # print basic info about compiled files
  - file build/${BINARY}
  # create hash for download verification
  - md5sum build/${BINARY} > build/${CHECKSUM}
  # update snapshots links
  - if [ -z "${TRAVIS_TAG}" ]; then mkdir -p upload/snapshots/${OS}/${ARCH} ;fi
  - if [ -z "${TRAVIS_TAG}" ]; then mkdir -p upload/snapshots/latest/${OS}/${ARCH} ;fi
  - if [ -z "${TRAVIS_TAG}" ]; then cp build/${BINARY} upload/snapshots/${OS}/${ARCH}/${DATETIME}_${TRAVIS_COMMIT:0:7}_${BINARY} ;fi
  - if [ -z "${TRAVIS_TAG}" ]; then cp build/${CHECKSUM} upload/snapshots/${OS}/${ARCH}/${DATETIME}_${TRAVIS_COMMIT:0:7}_${CHECKSUM} ;fi
  - if [ -z "${TRAVIS_TAG}" ]; then cp build/${BINARY} upload/snapshots/latest/${OS}/${ARCH}/${BINARY} ;fi
  - if [ -z "${TRAVIS_TAG}" ]; then cp build/${CHECKSUM} upload/snapshots/latest/${OS}/${ARCH}/${CHECKSUM} ;fi
  # update releases links
  - if [ -n "${TRAVIS_TAG}" ]; then mkdir -p upload/releases/{latest,${TRAVIS_TAG}}/${OS}/${ARCH} ;fi
  - if [ -n "${TRAVIS_TAG}" ]; then cp build/${BINARY} upload/releases/${TRAVIS_TAG}/${OS}/${ARCH}/${BINARY} ;fi
  - if [ -n "${TRAVIS_TAG}" ]; then cp build/${CHECKSUM} upload/releases/${TRAVIS_TAG}/${OS}/${ARCH}/${CHECKSUM} ;fi
  - if [ -n "${TRAVIS_TAG}" ]; then cp build/${BINARY} upload/releases/latest/${OS}/${ARCH}/${BINARY} ;fi
  - if [ -n "${TRAVIS_TAG}" ]; then cp build/${CHECKSUM} upload/releases/latest/${OS}/${ARCH}/${CHECKSUM} ;fi
  # add SFTP authentication key to the build environment
  - openssl aes-256-cbc -K $encrypted_1e5406d6c11a_key -iv $encrypted_1e5406d6c11a_iv -in mvdsv_builds.key.enc -out mvdsv_builds.key -d
  # set correct permissions on private key
  - chmod 600 mvdsv_builds.key
  # push built items to SFTP storage
  - sftp -q -i mvdsv_builds.key -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${SFTP_PORT} ${SFTP_USERNAME}@${SFTP_HOST}:/ <<< $'put -rp upload/*'
